name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Day 1
      run: cargo build --verbose
      working-directory: advent-2021-day-1
    - name: Run
      run: cargo run --verbose
