name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-day-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - uses: Swatinem/rust-cache@v1

    - name: Build Day 1
      run: cargo build --verbose
      working-directory: advent-2021-day-1
    - name: Run
      run: cargo run --verbose input
      working-directory: advent-2021-day-1
